### ISSUE TITLE
HttpClient with DefaultCredentials

### ISSUE THREAD

**Issue by MarcusKohnert** [dotnet/HttpRepl#112]
As I'm working in an enterprise environment I would like to be able to turn on `UseDefaultCredentials=true` on `HttpClient`.

Most of our HTTP endpoints use Kerberos Authentication (aka WindowsAuthentication in IIS). Those endpoints require that the HttpClient sends proper user authentication in it's requests.

**Comment by tlmii** [comment]
Closing this since the change was merged already.
