### ISSUE TITLE
Getting `Must specify a swagger document`

### ISSUE THREAD

**Issue by Tadimsky** [dotnet/HttpRepl#136]
Hey
I'm trying out httprepl and running into an issue when trying to use it right now.

This is what I'm doing:

```
dotnet httprepl https://dev.whiteboard.microsoft.com:9062/
https://dev.whiteboard.microsoft.com:9062/~ set swagger /swagger/v1.0/swagger.json
```

I then get this error: `Must specify a swagger document`

That is the relative URL to my swagger document and using Fiddler it seems like it's not even trying to make the request.

This is all that I was able to capture in Fiddler and it shows up before I use `set swagger`:

![image](https://user-images.githubusercontent.com/1149244/62419533-1a2b1b80-b637-11e9-936a-de9a83c11bc0.png)

**Comment by Tadimsky** [comment]
And interestingly, now it seems like each time I try to make a request, it tries to fetch the swagger file at the wrong location:

![image](https://user-images.githubusercontent.com/1149244/62419548-65ddc500-b637-11e9-88d8-8b280532583e.png)

**Comment by littlesmilelove** [comment]
I have the same problem.

**Comment by tlmii** [comment]
It looks like, at the moment, the `set swagger` command requires that the parameter be an absolute uri:

https://github.com/aspnet/HttpRepl/blob/25dba5cb4bee2a8f74938c4fc07f250190a412ca/src/Microsoft.HttpRepl/Commands/SetSwaggerCommand.cs#L245

That doesn't seem right to me, so we'll have to investigate. But for now, I think you might be able to get it working by using the absolute uri instead of the relative one. Can you confirm if that works for you?

**Comment by Tadimsky** [comment]
@tlmii that worked (well at least it didn't show an error).

The `dir` command is not showing anything though for me though.

**Comment by Tadimsky** [comment]
@tlmii that worked. It didn't show an error and the file was fetched (according to Fiddler).

However, I'm not able to explore the API. Using `dir` just prints nothing.

Also, side note: it seems like having trailing spaces after the swagger URL result in it failing to parse as well.

**Comment by littlesmilelove** [comment]
> @tlmii that worked. It didn't show an error and the file was fetched (according to Fiddler).
> 
> However, I'm not able to explore the API. Using `dir` just prints nothing.
> 
> Also, side note: it seems like having trailing spaces after the swagger URL result in it failing to parse as well.

The new issue may be fixed by this pull request [link](https://github.com/aspnet/HttpRepl/pull/139)
