### ISSUE TITLE
File extension on temp file for body

### ISSUE THREAD

**Issue by tommes** [dotnet/HttpRepl#186]
Great project,

as an idea, could you add an appropriate extension to the temp file name, so that an editor can provide colouring and intellisense for the body template?

Should be here:
https://github.com/dotnet/HttpRepl/blob/0189a224b07fa1b82b3cedf36886ede778e131a9/src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs#L202

Thanks!

**Comment by tlmii** [comment]
@tommes Good call. That should be a fairly easy change for a good amount of end-user value. I'll take a look.
