### ISSUE TITLE
Add Roslyn Analyzers to all projects and fix associated warnings/errors.

### ISSUE THREAD

**Issue by tlmii** [dotnet/HttpRepl#210]
Should be self-explanatory from the title.

**Comment by tlmii** [comment]
Removing  the 3.0 blocker tag since the existing issues are minimal and it'll be deferred until after release.

**Comment by bradygaster** [comment]
Let's get a list of examples of the errors and warnings we want to mitigate. Maybe a build log or something to use as a scenario.

**Comment by tlmii** [comment]
Turns out, this was already done in #249. Closing it, and removing it from the 3.2 milestone and blacklog.
