### ISSUE TITLE
Search for OpenAPI v3 filename

### ISSUE THREAD

**Issue by Tasteful** [dotnet/HttpRepl#248]
Regarding to [OpenAPI.v3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#document-structure) the recommendation is that the spec name should be `openapi.json` or `openapi.yaml`. Should that be added to the searchpath's below?

https://github.com/dotnet/HttpRepl/blob/53e84a988a96d2d959801f8205a8babdef56b873/src/Microsoft.HttpRepl/ApiConnection.cs#L21

**Comment by tlmii** [comment]
Good call. You're right it probably should be.
