### ISSUE TITLE
Unable to find swagger definition

### ISSUE THREAD

**Issue by jburman** [dotnet/HttpRepl#280]
**OS:** Win 10 Pro 1903 18362.418
PowerShell 5.1

dotnet --version
3.0.100

**Tool version:**
microsoft.dotnet-httprepl      3.0.47301      httprepl

**Issue:**
I spun up a new API project on .NET Core 3, using NSwag.AspNetCore 13.1.3. I'm able to browse site fine in swagger UI and call my api from browser etc. 
Swagger file is at: https://localhost:5001/swagger/v1/swagger.json

Trying to connect with repl gives me "Unable to find swagger definition" error.
Attempting to run ls gives error "No directory structure has been set, so there is nothing to list. Use the "set swagger" command to set a directory structure based on a swagger definition."

Attempting to run set swagger gives error:
"No matching command found
Execute 'help' to see available commands"

**Comment by tlmii** [comment]
Sorry for the delay in getting back to you on this. Have you had any more luck in the interim? Can you tell me the full connect command you're calling (or command line args if that's how you're doing it)? With the swagger location you've listed above, I'd expect that `connect https://localhost:5001` would work (setting the base address to the passed-in address and finding the swagger at the address you listed).

**Comment by jburman** [comment]
After testing a bit more tonight, I figured out that I've ended up with multiple ASP.NET Core dev certs on my machine and the one currently being used was not trusted. Adding it to trusted resolved the issue.

**Comment by tlmii** [comment]
Got it. Thanks for the follow-up! I'll close the issue.
