### ISSUE TITLE
httprepl nice idea, but why are error messages like fail to connect shown as stacktraces?

### ISSUE THREAD

**Issue by scottaddie** [dotnet/HttpRepl#304]
Issue originally opened by @mattiasw2 at https://github.com/aspnet/AspNetCore.Docs/issues/15936.

> For example, instead of "No connection ...." I get this
> 
> http://localhost:5000/&gt; options
> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
>  ---&gt; System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
> :
> :

**Comment by tlmii** [comment]
Thanks for the heads up @scottaddie. Definitely something we'd like to make better.
