### ISSUE TITLE
Support passing default credentials to a proxy

### ISSUE THREAD

**Issue by mungojam** [dotnet/HttpRepl#305]
We are behind a corporate proxy and so the tool isn't currently usable for us which is a shame as it's great :)

**Comment by tlmii** [comment]
Sorry it's taken us a while to get back to you. 

Default proxy support should already be in the tool. Under the hood, we're using [`HttpClient`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-3.1), and that picks up the [`DefaultProxy`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=netcore-3.1) automatically. I'll get that added to the documentation, but I'm curious what issues you ran into with your corporate proxy. It _should_ just pick up your system proxy, but you can also configure it directly via environment variables (see the [Remarks section](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=netcore-3.1#remarks) of the `DefaultProxy` docs).

**Comment by tlmii** [comment]
@mungojam Just following up here. I still need to get this added to the documentation. But do you have any additional details on what issues you ran into?

**Comment by mungojam** [comment]
Hiya, sorry haven't got around to looking into it again. I think the issue is more if you have a Windows authenticated proxy. .net core requires a one-liner to tell it to use the default credentials for the proxy but I'm not at my computer to point you to it. Will try to later 🙂

**Comment by mungojam** [comment]
You can see how it was added to sleet (following my request):

https://github.com/emgarten/Sleet/pull/126

**Comment by tlmii** [comment]
@mungojam Ah, so its the auth side that's the problem, not the use of the proxy itself. That makes sense. 

Thanks for the link. We've already got default cred support for the APIs themselves, It should be easy to add the call for the proxy too. Looks like we'll need a new preference (probably `httpClient.proxy.useDefaultCredentials` or similar) and then adding it when we construct the handler in [GetHttpClientWithPreferences](https://github.com/dotnet/HttpRepl/blob/01b7bd9f7e70caeb54edb2f8dd36453833994e78/src/Microsoft.HttpRepl/Program.cs#L149).

I'll see if we can sneak that in before 5.0
