### ISSUE TITLE
Does not wait for editor in some cases when doing a POST/PUT/etc

### ISSUE THREAD

**Issue by tlmii** [dotnet/HttpRepl#310]
HttpRepl version: 3.0.47301
VS Code version: 1.40.2
OS: Windows 10

If I have VS Code open, and VS Code is set to be the editor on the tool, the "template" file pops open in VS Code correctly, but the tab title for the file says "(deleted)" and the tool does not wait for the file to be closed, it just sends it right away and then deletes the file. 

If I don't have VS Code open, and so it is launched when executing a POST, the process seems to work as expected.

**Comment by bradygaster** [comment]
investigate for 3.1 - if possible mark it otherwise continue to watch for reports on this.

**Comment by vijayshinva** [comment]
![image](https://user-images.githubusercontent.com/16094361/86951181-c9894000-c16e-11ea-8452-ba5e16d54f1a.png)

I am facing a similar issue. The moment I type the post command and hit enter this error is displayed. The vscode window opens a second latter.

**Comment by tlmii** [comment]
@vijayshinva 

I _think_ this might be a different bug, because in my case the file is still there on disk when the read occurs, I'm just not given the opportunity to modify it before it is read. It seems like in your case the file is deleted before it is read - or perhaps it is never actually created and written to. But it could be related, somehow. 

Does this happen the same way whether or not you have VS Code already open when you execute the command? 
Does the same thing occur if you set your editor to be notepad instead of vs code?

**Comment by tlmii** [comment]
I'll need to do more digging on this to see if it is reasonable to pass this command ourselves or handle it more directly, but here's the workaround:

in addition to setting `editor.command.default`, also set `editor.command.default.arguments` to `-w`:

```console
pref set editor.command.default.arguments "-w"
```

This will tell VS Code to wait for you to close the editor before returning, even if it is the case where it opens it in an existing window.

**Comment by tlmii** [comment]
@bradygaster This is probably more of a question for you. It seems like we would always want someone who sets their editor to  VS Code to _also_ set the default arguments to add the `-w` switch. 

Should we inspect what they set as their editor and suggest it via text on the screen? Should we automatically add it (if the args are otherwise empty when they set the editor)? Should we just put it in the documentation?

**Comment by bradygaster** [comment]
> This is probably more of a question for you. It seems like we would always want someone who sets their editor to VS Code to also set the default arguments to add the -w switch.

Yes and we could document that on the VS Code site or in an extension if need be.

> Should we inspect what they set as their editor and suggest it via text on the screen? 

That'd be ideal but I wouldn't block on other larger issues if this becomes a time vortex.
