### ISSUE TITLE
Improve initial header output when repl starts

### ISSUE THREAD

**Issue by timheuer** [dotnet/HttpRepl#336]
When the repl tool is started we should emit some more helpful information on how to use it, at a minimum a link to the docs of where to get more information, e.g., an aka.ms link to helpful information. - use https://aka.ms/httprepl

**Comment by bradygaster** [comment]
@timheuer - what's the status of the pull request on this? We'd like to get this one wrapped up - let us know next steps as you see them

**Comment by tlmii** [comment]
Completed #337, so closing this.
