### ISSUE TITLE
Drop netcoreapp3.0, add netcoreapp3.1

### ISSUE THREAD

**Issue by tlmii** [dotnet/HttpRepl#348]
Since .NET Core 3.0 is out of support already and 3.1 is the LTS, should we update the `TargetFrameworks` to drop netcoreapp3.0 and add netcoreapp3.1?

I already made the change to add net5 when arcade switched us to using the .net 5 sdk, so we're ready for that (which we needed to be since we have major version roll forward disabled).

@timheuer ?

**Comment by timheuer** [comment]
Agreed we should drop. I think netstandard target needs examination as well

-th
________________________________
