### ISSUE TITLE
Make well-known Open API description locations list more easily configurable

### ISSUE THREAD

**Issue by tlmii** [dotnet/HttpRepl#360]
Right now we have a hard-coded list of well-known URLs to query when looking for the OpenAPI description file:

https://github.com/dotnet/HttpRepl/blob/39f01df90487272f2948b9fce703d4073fad1297/src/Microsoft.HttpRepl/ApiConnection.cs#L21

We also have a(n undocumented) preference the user can set - `swagger.searchPaths` - to override the defaults completely. 

It would be nice to allow the user to add entries to the list if they have a common pattern they use/see/like without blowing away the existing list (or needing to type it all back in). It might also be nice to allow them to remove entries from the list if they know they'll never encounter them to prevent extra network traffic when trying to connect. Same thing could go for just reordering them.

**Comment by tlmii** [comment]
My proposal here is this:

Two additional preferences, so that the complete set is
1. `swagger.removeFromSearchPaths` - pipe-delimited list that removes specific entries from the default list
2. `swagger.addToSearchPaths` - pipe-delimited list that adds new entries to the default list
3. `swagger.searchPaths` - the existing preference, which we'll document. A pipe-delimited list that overrides the default list (and the other two preferences) altogether.

**Comment by bradygaster** [comment]
hugely agree with this as a feature. love the hyper-configurability of it.
