### ISSUE TITLE
Verbosity setting for connect command?

### ISSUE THREAD

**Issue by tlmii** [dotnet/HttpRepl#373]
Right now, the `connect` command is pretty quiet in terms of the output. It tells you the results (which base address and open api address it picked) when it finishes, but otherwise there is no real output.

I propose that we have add a verbose output mode for the command. So the two output modes would be:

- Standard: Same as now plus adding validation information (see #372) for the selected OpenAPI description if one was found.
- Verbose: Log all of the OpenAPI description endpoints we try and why they were not selected (404 Not Found or 401 Not Authorized status codes, or no ApiDefinitionReader could handle what was returned) along with validation errors.

Standard would be the default and we could add a `--verbose|-v` option to the command.

@bradygaster This is more or less what I was talking about when we discussed the SSL issues you were having. Right now the tool just fails silently. This would at least point the user in the right direction even if we can't fix it for them.

**Comment by bradygaster** [comment]
WHEN?
