### ISSUE TITLE
POST requests issued immediately if editor is already opened

### ISSUE THREAD

**Issue by bellons91** [dotnet/HttpRepl#378]
I've set up VS Code as my default editor with

`pref set editor.command.default "C:\Users\my-user\AppData\Local\Programs\Microsoft VS Code\Code.exe"`.

I tried HttpRepl while I was using VS Code for other reasons, and I noticed that when I run a `post` command, HttpRepl 
1. creates the temporary file
2. sends the request to the endpoint with empty values
3. lets me edit the tmp file
4. when I save the tmp file, nothing happens (because the request has already been completed in the step 2)

On the contrary, if I don't use VS Code for other reasons, everything works fine.

**Comment by tlmii** [comment]
This seems to be the same thing as #310. I just haven't had a chance to dig into it and was kind of surprised no one else was reporting it or complaining about it. 

As far as I can tell, it has to do with the way VS Code will redirect a new launch of the app to the existing one if you've configured it that way (and I think its the default). So we wait on the process, but the launched process exits after it redirects. I'll close this as a duplicate, but see if I can prioritize the overall issue.

**Comment by tlmii** [comment]
FYI @bellons91, I posted a a workaround in the other issue: https://github.com/dotnet/HttpRepl/issues/310#issuecomment-674581115
