### ISSUE TITLE
Validate OpenAPI Description during verbose connect

### ISSUE THREAD

**Issue by tlmii** [dotnet/HttpRepl#406]
This is related to #372 but is a little more simple (no new command). When #405 goes in (to resolve #373) we'll have a good location to put some of the validation information that comes "for free" with OpenAPI.NET ([the OpenApiDiagnostics.Error property](https://github.com/microsoft/OpenAPI.NET/blob/2db9643cdf99ad2135de897a7fcd530da3e2c8b5/src/Microsoft.OpenApi.Readers/OpenApiDiagnostic.cs#L18)).

**Comment by bradygaster** [comment]
I obviously like this. :)
