### ISSUE TITLE
--response option on HTTP commands only writes the body

### ISSUE THREAD

**Issue by tlmii** [dotnet/HttpRepl#407]
It looks like we have a bug where using the --response option only outputs the body. Technically it writes the headers, then overwrites with the body:

https://github.com/dotnet/HttpRepl/blob/01b7bd9f7e70caeb54edb2f8dd36453833994e78/src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs#L398

This came up while investigating #404 to see what the delineator between the two sections is.

The bug has been present since 3.0 previews, so this is probably a pretty good indication that the --response option is not being used right now. Fix? Or cut?

@bradygaster

**Comment by bradygaster** [comment]
I argue cut. closing as such
