### ISSUE TITLE
Console buffer size exceeded with path to default installation location VS Code.

### ISSUE THREAD

**Issue by mikevankuik** [dotnet/HttpRepl#458]
While trying to add the path to the location where I have VS Code installed (my editor of choice) the console buffer get exceeded according to the application.

In plain engish, I would like to be able just to use VS Code as my editor but I can't set it.

![image](https://user-images.githubusercontent.com/29262650/101631965-7cfba680-3a25-11eb-8e60-d88734b77c93.png)

**Comment by tlmii** [comment]
This looks like the same thing as #443. We are working on a fix right now (#457).

As a workaround for now, exit the tool, then run it from a vanilla cmd.exe prompt and set the editor the way you're doing it, then reload it in powershell in Windows Terminal.
