### ISSUE TITLE
Cannot run Microsoft.dotnet-httprepl 6.0.0 with dotnet 7.0 (at Ubuntu 22.04)

### ISSUE THREAD

**Issue by darkcompet** [dotnet/HttpRepl#592]
Microsoft.dotnet-httprepl 6.0.0 does work with dotnet 6.0 as so far, but it seems not compatible with dotnet 7.0.
Here is detail message:

You must install or update .NET to run this application.

App: /home/ubuntu/.dotnet/tools/httprepl
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  7.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

How should I fix this issue, I really need httprepl for our production now.
Thanks in advance !

**Comment by tlmii** [comment]
I've got a PR out (#594) that will address this.

**Comment by tlmii** [comment]
@darkcompet FYI, a preview build of 7.0 is available on nuget now: https://www.nuget.org/packages/Microsoft.dotnet-httprepl/7.0.0-preview.22601.1. Probably a week or so before a final build is out

**Comment by darkcompet** [comment]
Hi, I have run with v7.0 preview and it goes well as expected !
Thanks @tlmii so much !
