### ISSUE TITLE
HttpRepl does not support .NET 8

### ISSUE THREAD

**Issue by simonjha** [dotnet/HttpRepl#630]

**Comment by tlmii** [comment]
The first preview of HttpRepl 8.0 (w/ support for .NET 8) is now live: https://www.nuget.org/packages/Microsoft.dotnet-httprepl/8.0.0-preview.23564.1

**Comment by sliekens** [comment]
@tlmii I tested and it works with .NET 8.0.7 (sdk 8.0.303)

Can you promote this to stable? As you are aware, .NET 7 has reached end of support, so I would like to remove it from my dev machine.

**Comment by tlmii** [comment]
@sliekens Would you mind validating the latest build published today? `8.0.0-preview.24366.2`? For various internal infrastructure reasons I can no longer promote the last one to stable. There shouldn't be any functional changes between that build and this one - just some build tool updates. I can promote this one to stable quickly.

**Comment by sliekens** [comment]
@tlmii works on my machine

![image](https://github.com/user-attachments/assets/1f660105-3663-488b-8378-9fd236f98278)

**Comment by tlmii** [comment]
Here you go: https://www.nuget.org/packages/Microsoft.dotnet-httprepl/8.0.0
