### ISSUE TITLE
Verify and document supported EndpointMetadataReader implementation

### ISSUE THREAD

**Issue by bhsubra** [dotnet/HttpRepl#92]
Currently there are three end point metadata readers:
1.  OpenApiV3EndpointMetadataReader
2.  SwaggerV1EndpointMetadataReader
3. SwaggerV2EndpointMetadataReader

We need to create site for each of these endpoints and validate the expected schema. We also need to document the same.

**Comment by tlmii** [comment]
Closing this as there are no longer three different readers. Just the one based on OpenAPI.NET.
